### ISSUE TITLE
Syntax error when python -m pythorrent -h is run

### ISSUE THREAD

**Issue by tejt99** [yamatt/python-pythorrent#3]
Hi I am just fiddling around with this and when I run `python -m pythorrent -h` I get a large stream of errors:

> Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/theoturner/Downloads/python-pythorrent/pythorrent/__main__.py", line 16, in <module>
    from .torrent import Torrent
  File "pythorrent/torrent.py", line 26, in <module>
    from .peer_stores import store_from_url
  File "pythorrent/peer_stores.py", line 57
    class Tracker(object)
                        ^
SyntaxError: invalid syntax

I am not sure what this means. At all, whatsoever.
I am using mac os high sierra.
Thanks in advance

**Comment by yamatt** [comment]
hi @tejt99. I'm very appreciative of you reporting this. Unfortunately I'm not in a position to support this project any more, but I am glad people are interested in it.

The issue with the line 57 you are seeing are due to a `:` missing from the end of it.

I would very much appreciate it if you were able to provide a Pull Request for the change and any other issues you may find so that others may benefit from it.

I hope you get some value from it.

**Comment by tejt99** [comment]
Hi thanks I don't have permission for pull requests. I now get the error: 

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/theoturner/Downloads/python-pythorrent-master/pythorrent/__main__.py", line 16, in <module>
>     from .torrent import Torrent
>   File "/Users/theoturner/Downloads/python-pythorrent-master/pythorrent/torrent.py", line 154
>     lambda (url,): url, metainfo['announce-list']
>            ^
> SyntaxError: invalid syntax

I assume this is because of lambda, but I have no experience with this function so could I ask for your advice please. Thanks.

**Comment by tejt99** [comment]
Thanks I think I was just being stupid. After this I worked through all the other errors, which I think were mostly just updating py2 to py3. When I try to create a Pull Request the new request is greyed out, is this just me or am I missing something. Thanks for the speedy reply.

**Comment by tejt99** [comment]
I have created 3 new pull requests with, I think, everything I changed.

**Comment by tejt99** [comment]
Also the pip install doesn't work but I am unsure how that would be fixed

**Comment by tejt99** [comment]
Please see the error on #7
